version: "3.9"
services:
  auth-service:
    build: .
    ports: ["4001:4001"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4001
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./:/app
      - /app/node_modules
    profiles: ["standalone"]
